#@base_url = http://localhost:2552/api

@base_url = http://65.0.21.177:2552/api

###

POST {{base_url}}/auth/sign-up HTTP/1.1
content-type: application/json

{
    "firstName": "admin",
    "lastName": "admin",
    "userName": "admin",
    "email": "admin@test.com",
    "phone": 9090911111,
    "password": "admin",
    "role": "609a3fa0a716673990873c15"
}

###

POST {{base_url}}/auth/login HTTP/1.1
content-type: application/json

{
    "userName": "sanju22",
    "password": "11111"
}

###

GET {{base_url}}/user HTTP/1.1
content-type: application/json


###
PUT {{base_url}}/user/ HTTP/1.1
content-type: application/json

{
    "firstName": "mahendra",
    "lastName": "bhau",
    "phone": 9090911110,
    "status": true,
    "_id": "6099636fcfc7fc7504549e98"
}

###
DELETE {{base_url}}/user/ HTTP/1.1
content-type: application/json

{
    "status": true,
    "_id": "6093d5329d21796ff463e422"
}

###

GET {{base_url}}/user/role HTTP/1.1
content-type: application/json

###


POST {{base_url}}/user/role HTTP/1.1
content-type: application/json

{
    "title": "admin"
}